### ISSUE TITLE
Provider API

### ISSUE THREAD

**Issue by alexcouper** [pretenders/deploystream#26]
I've had a look around at different options being used and came across this:
http://stackoverflow.com/questions/2768104/how-to-create-a-flexible-plug-in-architecture

whose first answer led me to look at this:
http://pytest.org/latest/plugins.html#well-specified-hooks

I think that looks really elegant from a contributors perspective. What do you think about that kind of architecture?

**Comment by txels** [comment]
The distribute/setuptools `entry_points` approach sounds nice, I didn't know of that.
How do you think of mapping the `py.test` approach to our project?
