### ISSUE TITLE
Change plugin initialisation

### ISSUE THREAD

**Issue by alexcouper** [pretenders/deploystream#37]
We currently init all the plugins in the constructor of deploystream with all config info.

This has to change as we are wanting multiple users.

either.

a) Continue with init there, but pass all configuration into each method call.
b) Create the plugins as they're needed, for each request, discarding them afterwards.
c) Something else?

**Comment by alexcouper** [comment]
Probably related to #17

**Comment by alexcouper** [comment]
I'm going to have to take care of this as part of #28 

I'm going with (b).

**Comment by txels** [comment]
Why not session? Initialise user's plugins upon login...
